# NUMPY

In [1]:
# WHY USE NUMPY

# Numpy provides efficient storage.
# it also provides better ways of handling data for processing.
# it is fast.
# it is easy to learn.
# numpy uses relatively less memory to store data.


# Array VS List

In [2]:
# An Array is a grid of values and it contains information about  the raw data,how to locate an element,and how to intrupt an element

# -> All elements of an array are of same data type.
# -> Elements of an array are sorted in contiguous memory locations.
# -> Array are static and can not be resized once they are created.
# -> Arrays support element wise operations.
# -> Numpy array takes up less space in memory.
# ...................................................................
# -> List can have elements of diffrent data types.
# -> List elements are not stored in contiguously in memory.
# -> List can be resized and modified easily.
# -> List do not support element wise operations.
# -> More space in memory.

In [3]:
h=[10,20,30,40,50]
print(h)
# print(h+2)
temp=[]
for i in h:
    temp.append(i+2)
print(temp)

[10, 20, 30, 40, 50]
[12, 22, 32, 42, 52]


In [4]:
import numpy as np

In [5]:
p=[10,20,30,40,50]
print(p,type(p))
q=np.array(p)
print(q,type(q))
print(q+2)

[10, 20, 30, 40, 50] <class 'list'>
[10 20 30 40 50] <class 'numpy.ndarray'>
[12 22 32 42 52]


In [6]:
k=[11,12,76,56,34]
print(k,type(k))
print(k*2)
j=np.array(k)
print(j)
print(j*2)
print(type(j))
print("shape" ,j.shape)
print(j.ndim)

[11, 12, 76, 56, 34] <class 'list'>
[11, 12, 76, 56, 34, 11, 12, 76, 56, 34]
[11 12 76 56 34]
[ 22  24 152 112  68]
<class 'numpy.ndarray'>
shape (5,)
1


In [7]:
a=[12,22,33,45,67,78,67]
print(a,type(a))
print(a*3)
b=np.array(a)
print(b)
print(b*3)
print(type(b))
print("shape",b.shape)
print(b.ndim)

[12, 22, 33, 45, 67, 78, 67] <class 'list'>
[12, 22, 33, 45, 67, 78, 67, 12, 22, 33, 45, 67, 78, 67, 12, 22, 33, 45, 67, 78, 67]
[12 22 33 45 67 78 67]
[ 36  66  99 135 201 234 201]
<class 'numpy.ndarray'>
shape (7,)
1


In [8]:
l1=[[11,12,13],[21,23,24],[23,56,78]]
print(l1)
print(len(l1)) 
matrixx=np.array(l1)
print(matrixx)
print(matrixx.shape)
print(matrixx.ndim)          #--->ndim is number of dimension

[[11, 12, 13], [21, 23, 24], [23, 56, 78]]
3
[[11 12 13]
 [21 23 24]
 [23 56 78]]
(3, 3)
2


In [9]:
range(10,20)
for i in range(10,20):                 #This is lenthy process to solve its shortcut is arange predefined function
    print(i,end=" ")
print()
print(list(range(10,16)))
print(np.array(list(range(10,20)))*5)

10 11 12 13 14 15 16 17 18 19 
[10, 11, 12, 13, 14, 15]
[50 55 60 65 70 75 80 85 90 95]


In [10]:
np.arange(20,30,2)                        

array([20, 22, 24, 26, 28])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
for i in np.arange(10,20,2):
    print(i)

10
12
14
16
18


In [13]:
for i in np.arange(115,9,-20):
    print(i)

115
95
75
55
35
15


In [14]:
a = np.zeros(5)
print(a)
print(type(a))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [15]:
# np.zeros(5,3)   Error    we cant send more values in one time for this we can put many files in one file and send them
np.zeros([5,3])  # list

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((5,3)) #tuple

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((5,6))+1

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [19]:
np.ones((5,6))*2

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [1]:
from PIL import Image
r= Image.open(r"C:\Users\lenovo\Downloads\picture.webp")    #IMAGE importer  
r
a=np.array(r)
a
img.show()

In [22]:
np.linspace(0,10,5)      #start ,end, partition divde the range in equal parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(11,99,6)

array([11. , 28.6, 46.2, 63.8, 81.4, 99. ])

In [24]:
np.eye(5)         # identity matrix  diagonals are 1 rest are 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(8)       #identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.randint(10,50,3)     #generate random data

array([16, 16, 43])

In [27]:
arr1=np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
arr1.shape

(12,)

In [29]:
arr2=arr1.reshape(4,3)#4 is rows and 3 is columns
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
arr2.shape

(4, 3)

In [31]:
arr2.min()

0

In [32]:
arr2.max()

11

In [33]:
arr2.sum()

66

# OPERATIONS

In [34]:
a=np.arange(15,21)
b=np.arange(25,31)
c=10
d=np.arange(5,8)
print(a)
print(b)
print(d)

[15 16 17 18 19 20]
[25 26 27 28 29 30]
[5 6 7]


In [35]:
 for i in d:
     print(i+a)

[20 21 22 23 24 25]
[21 22 23 24 25 26]
[22 23 24 25 26 27]


In [36]:
a+c

array([25, 26, 27, 28, 29, 30])

In [37]:
# a+d error becoz a contain 6 values nd d contain 3 values

In [38]:
a=np.arange(15,21)
b=np.arange(25,31)
print(a)
print(b)

[15 16 17 18 19 20]
[25 26 27 28 29 30]


In [39]:
a+b

array([40, 42, 44, 46, 48, 50])

In [40]:
for i in d:
    print(i+a)

[20 21 22 23 24 25]
[21 22 23 24 25 26]
[22 23 24 25 26 27]


In [41]:
a

array([15, 16, 17, 18, 19, 20])

In [42]:
a*a

array([225, 256, 289, 324, 361, 400])

In [43]:
a/a

array([1., 1., 1., 1., 1., 1.])

In [44]:
b=np.arange(6)

In [45]:
b**2

array([ 0,  1,  4,  9, 16, 25])

In [46]:
b**3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [47]:
b**0.5 #(square root)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [48]:
b**(1/3)

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
       1.70997595])

In [49]:
np.sqrt(b) #(square root)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [50]:
np.exp(b)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [125]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245],
       [3.13549422, 3.17805383, 3.21887582],
       [3.25809654, 3.29583687, 3.33220451],
       [3.36729583, 3.40119738, 3.4339872 ]])

In [126]:
np.log(a)

array([[2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176],
       [2.94443898, 2.99573227, 3.04452244]])

In [52]:
np.sin(b)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [53]:
a=np.random.randint(10,100,12).reshape(4,3)
a

array([[25, 53, 71],
       [30, 86, 65],
       [37, 30, 52],
       [33, 71, 16]])

In [54]:
b=np.random.randint(10,100,15).reshape(3,5)
b

array([[40, 34, 37, 14, 28],
       [72, 62, 28, 61, 45],
       [16, 44, 42, 36, 89]])

In [55]:
a.dot(b) #Returns a dot product of two arrays.

array([[ 5952,  7260,  5391,  6139,  9404],
       [ 8432,  9212,  6248,  8006, 10495],
       [ 4472,  5406,  4393,  4220,  7014],
       [ 6688,  6228,  3881,  5369,  5543]])

In [56]:
a=np.array( [[1,2,3],[4,5,6]] )
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
b=np.array( [[10,11],[20,21],[30,31]])
b

array([[10, 11],
       [20, 21],
       [30, 31]])

In [58]:
a.dot(b) #(dot use for multiplication of matrix)

array([[140, 146],
       [320, 335]])

In [ ]:
a = np.array([[]])

In [59]:
c=np.array( [[10,11,12],[20,21,22]])
c

array([[10, 11, 12],
       [20, 21, 22]])

In [60]:
np.vdot(a,c) #(vdot use for sum of matrix after multiplication)

385

In [61]:
b=np.array( [[1, 2, 3],[4,5,6]] )
b                 

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
c=np.array( [[3,4,5],[7,9,8]])
c

array([[3, 4, 5],
       [7, 9, 8]])

In [63]:
np.vdot(b,c)

147

In [64]:
a=np.array([[12,2,3,4],[6,8,9,5]])
a

array([[12,  2,  3,  4],
       [ 6,  8,  9,  5]])

In [65]:
b=np.array([[23,12,3,4],[4,5,6,7]])
b

array([[23, 12,  3,  4],
       [ 4,  5,  6,  7]])

In [66]:
c=np.array([[2,3,4,5],[23,6,8,9]])
c

array([[ 2,  3,  4,  5],
       [23,  6,  8,  9]])

In [67]:
np.vdot(a,c)

365

In [68]:
a=np.array([[1,2,3],[4,5,6]])
print(a,"\n")
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1 2 3]
 [4 5 6]] 

(2, 3)
2
int32


In [69]:
a=np.arange(12)
print("before :\n",a)
a.shape=(4,3)
print("\nafter :\n",a)

before :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

after :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [70]:
a=np.arange(12)
print("before :\n",a)
b=a.reshape(4,3)   #(if we don't want to change the original data then we use reshape function)
print(b)
print("\n",a)

before :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
a=np.arange(24)
print("a ndim is :",a.ndim)
print("before :\n",a)
b=a.reshape(3,2,4)
print("nb ndim is :",b.ndim)
print(b)

a ndim is : 1
before :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
nb ndim is : 3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [72]:
l=[1,2,3,4,5]
print(np.array(l))
print(np.asarray(l))

[1 2 3 4 5]
[1 2 3 4 5]


In [73]:
a=np.array([12,34,56,78])
print(a.itemsize)
print(a.dtype)

4
int32


In [74]:
a=np.array([12,34,56,78],dtype=np.int64)
print(a)
print(a.itemsize)
print(a.dtype)

[12 34 56 78]
8
int64


In [75]:
a=np.array([12,34,56,78],dtype=float)
print(a)
print(a.itemsize)
print(a.dtype)

[12. 34. 56. 78.]
8
float64


# LIST SLICING

In [76]:
import numpy as np

In [77]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [78]:
print(a[:3])
print(a[2:7])
print(a[7:])
print(a[7:10])
print(a[-3:])
print(a[0::2])
print(a[2::3])
print(a[0:3])

[10 11 12]
[12 13 14 15 16]
[17 18 19]
[17 18 19]
[17 18 19]
[10 12 14 16 18]
[12 15 18]
[10 11 12]


In [79]:
a=np.arange(10,20)
b=np.arange(50,60)
c=np.arange(70,80)
print(a)
print(b)
print(c)
d=slice(2,7,1)
print(a[d])
print(b[d])
print(c[d])

[10 11 12 13 14 15 16 17 18 19]
[50 51 52 53 54 55 56 57 58 59]
[70 71 72 73 74 75 76 77 78 79]
[12 13 14 15 16]
[52 53 54 55 56]
[72 73 74 75 76]


In [80]:
ar=np.arange(10,34).reshape(6,4)
print(ar)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


In [81]:
print(ar[ : , : ])
print("\n")
print(ar[ : : , : : ])
print("\n")
print(ar[...])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


In [82]:
print(ar[:3,:])
print(ar[:,:3])
print(ar[:3,:3])
print(ar[0::2,1::2])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 11 12]
 [14 15 16]
 [18 19 20]
 [22 23 24]
 [26 27 28]
 [30 31 32]]
[[10 11 12]
 [14 15 16]
 [18 19 20]]
[[11 13]
 [19 21]
 [27 29]]


In [83]:
 print(ar)
print(ar.reshape(2,3,4))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]
[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]
  [30 31 32 33]]]


In [84]:
print(ar.reshape(1,24)) #single 1 dimension

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]]


In [85]:
print(ar.reshape(24,1))

[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]]


In [86]:
print(ar.flatten())  #convert into 1 d

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]


In [87]:
print(ar.flat[12]) #fetch the positional value

22


In [88]:
print(ar.flat[7])

17


In [89]:
print(ar)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


In [124]:
print(ar.T) #transpose converts into row into column

[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [120]:
a=np.arange(10,22).reshape(4,3)
b=np.arange(20,32).reshape(4,3)

In [92]:
print(a)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [93]:
print(b)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


In [121]:
np.vstack((a,b)) 

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])

In [95]:
np.hstack((a,b)) #converts rows into coloumn,converts into horizontally

array([[10, 11, 12, 20, 21, 22],
       [13, 14, 15, 23, 24, 25],
       [16, 17, 18, 26, 27, 28],
       [19, 20, 21, 29, 30, 31]])

In [122]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [107]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
ar.sum(axis=0)        #axis 0 sums the values columnwise

array([12,  8,  9])

In [99]:
ar.sum(axis=1)       #axis 1 sums the values row wise

array([ 6, 15,  8])

In [100]:
ar.nbytes

36

In [123]:
one = np.array([65,34,635,23,9])

In [102]:
one.argmax()

2

In [103]:
one.argsort()   #sort the values in increasing order

array([4, 3, 1, 0, 2], dtype=int64)

In [104]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [108]:
ar2 = np.array([[1,2,3],[5,6,7],[8,7,9]])

In [109]:
ar2

array([[1, 2, 3],
       [5, 6, 7],
       [8, 7, 9]])

In [110]:
ar+ar2

array([[ 2,  4,  6],
       [ 9, 11, 13],
       [15,  8,  9]])

In [111]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [112]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)